name: DataWeb
channels:
- defaults
dependencies:
- python=2
- flask
- lxml
- markdown2
- bokeh=0.12.14
- pip:
  - pygal==2.3.1
  - Flask==0.12
  - MarkupSafe==0.23
  - py==1.4.32
  - blinker==1.4
  - decorator==4.0.11
  - Flask==0.12
  - Flask-Login==0.4.0
  - Flask-Mail==0.9.1
  - Flask-User==0.6.9
  - Flask-SQLAlchemy==2.1
  - Flask-WhooshAlchemy==0.56
  - Flask-WTF==0.14.2
  - flipflop==1.0
  - pbr==1.10.0
  - six==1.10.0
  - SQLAlchemy==1.1.5
  - sqlalchemy-migrate==0.10.0
  - sqlparse==0.2.2
  - Tempita==0.5.2
  - Whoosh==2.7.4
  - WTForms==2.1
  - MySQL-python==1.2.5
  - enum34==1.1.6

